#import anchors.yaml
#benchmark netperf

netperf:
  description: run netperf TCP CRR
  flag_matrix: inter_region
  flag_matrix_filters:
    inter_region: "zones < extra_zones"
  flag_matrix_defs:
    inter_region:
      zones: [us-central1-c]
      extra_zones: [us-east1-b]
      machine_type: [n1-standard-16]
  flags:
    cloud: GCP
    netperf_histogram_buckets: 1000
netperf_benchmarks: TCP_CRR
