---
- hosts: all
  become: no
  #strategy: debug
  #gather_facts: False
  gather_facts: True

  vars_files:
    - vars/main.yml

  roles:
    - role: ansible-role-core
      become: False

    - role: ansible-role-emane
      become: False

      #  tasks:
    # experiment stuff
    #- include_tasks: setup.yml
    #  tags: [models,run,db]
    #- include_tasks: run.yml 
    #  tags: run   
