# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "mininet-wifi" do |config|
  
  #config.vm.box = "generic/ubuntu1804"
  config.vm.box = "ubuntu/bionic64"
  config.vm.synced_folder '.', '/vagrant', disabled: true
  config.ssh.insert_key = false
   
  #config.vm.provider :virtualbox do |vb|
  #  vb.gui = true
  #end
 
  config.vm.hostname = "mininet-wifi" 
  config.vm.network :private_network, ip: "192.168.6.6"
  
  # Run Ansible from the Vagrant Host
  config.vm.provision "ansible" do |ansible|
    ansible.compatibility_mode = "2.0"
    ansible.playbook = "playbooks/provision.yml"
    ansible.inventory_path = "inventory"
    ansible.limit = "all"
    ansible.verbose = false 
  end

end

end
