# setup some mulvals
# copies models to remote, installs packages, prepares to run 

- name: remove old models dir
  file:
          path: "{{mulval_models_dir}}"
          state: absent
  tags: [models,run,clean]

- name: remove old rules dir
  file:
          path: "{{mulval_custom_rules_dir}}"
          state: absent
  tags: [models,run,clean]

- name: mkdir -p dirs before copying
  file: 
    path: "{{mulval_models_dir}}/{{(item|basename|splitext)[0]}}/{{(item|basename|splitext)[0]}}_out"
    state: directory
    mode: 0755
  with_fileglob:
     - "{{mulval_models_src_dir}}/*"
  tags: [models,run]

- name: mulval models dir
  debug: 
    msg: "{{mulval_models_src_dir}}"
  tags: [models,run]

- name: get list of file paths
  delegate_to: localhost
  find: 
    paths: "files/{{mulval_models_src_dir}}"
    #paths: "files/"
    patterns: '*.p,*.P'
    recurse: yes
    file_type: file
  register: find_results
  tags: [models,run]

- name: what we found
  debug: 
    msg: "{{ item.path | relpath('files')}}"
  with_items: "{{find_results.files}}"
  tags: models

- name: copy models to remote in individual directories (mulval output is noisy)
  copy:
    #src:  "{{item.path | relpath('files')}}"
    src:  "{{item.path | relpath('{{mulval_models_src}}')}}"
    dest:  "{{mulval_models_dir}}/{{(item.path|basename|splitext)[0]}}"
  with_items: "{{find_results.files}}"
  tags: [models,run]

- name: copy custom rules to remote
  copy:
    src:  "{{mulval_custom_rules_src}}/"
    dest: "{{mulval_custom_rules_dir}}"
  tags: [models,run]

- name: concatenate custom rules (MulVal only takes 1)
  assemble:
    src: "{{mulval_custom_rules_dir}}" 
    dest: "{{mulval_custom_rules_dir}}/custom_rules.P"
  tags: [models,run]
  when: mulval_custom_rules_strategy == 'all' # make this too for testing

- name: copy scripts to remote
  copy:
    src: "{{ item }}"
    dest: "{{mulval_results_dir}}"
    mode: 0755
  with_items:
    - mcsim.r
    - genTransMatrix.py
    - scoreDict.yml
    - requirements.txt
  tags: [models, run]


- name: Install packages to run scripts
  become: True
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - libmysqlclient-dev
    - python3-mysqldb
    - python3-pandas
    - r-base
    - python3-yaml
    - python3-pip
    - graphviz
    - libgraphviz-dev
    - pkg-config
  tags: [models, run]

- name: install pip3 requirements
  pip:
    requirements: "{{mulval_results_dir}}/requirements.txt"
    executable: pip3
  tags: [models, run]


- name: Install  R packages
  become: True
  command: /usr/bin/Rscript --slave --no-save --no-restore-history -e "if (! ('{{item}}' %in% installed.packages()[,'Package'])) install.packages(pkgs='{{item}}', repos=c('http://cran.rstudio.com'))"
  with_items:
    - optparse
    - rPython
  tags: [models, run]

      # moved to mulval role for now
      #- name: sync mulval nvd db (set mulval_sync_nvd to False to disable)
      #shell: "/bin/bash {{mulval_home}}/utils/nvd_sync.sh"
      #args:
      #chdir: "{{mulval_home}}/utils"
      #when: mulval_sync_nvd == True
      #tags: [db]
