#import anchors.yaml
#benchmark iperf
iperf:
  flag_matrix: fmatrix
  flag_matrix_filters:
      fmatrix: "zones < extra_zones"
  flag_matrix_defs: 
    fmatrix:
      zones: *gcp_zones_all_conus
      extra_zones: *gcp_zones_all_conus
      machine_type: *gcp_machine_types_standard
      iperf_sending_thread_count: *iperf_sending_thread_count_1_5
  vm_groups:
    vm_1:
      vm_spec: *default_machine
      disk_spec: *default_50_gb
    vm_2:
      vm_spec: *default_machine
      disk_spec: *default_50_gb
      
