#import anchors.yaml
#benchmark iperf

iperf:
  flag_matrix: fmatrix
  flag_matrix_filters:
      fmatrix: "zones < extra_zones"
  flag_matrix_defs:
      fmatrix:
        zones: *gcp_zones_central1
        extra_zones: *gcp_zones_central1
        machine_type: [n1-standard-16]
        
  flags:
    cloud: GCP
    iperf_sending_thread_count: 5
    iperf_runtime_in_seconds: 60