#import anchors.yaml
#benchmark iperf

iperf:
  flag_matrix: inter_region
  flag_matrix_filters:
    inter_region: "zones < extra_zones"
  flag_matrix_defs:
    inter_region:
      zones: [us-central1-c, us-east1-b, us-east4-c, us-west1-b]
      extra_zones: [us-east1-b, us-east4-c, us-west1-b, us-west2-a]
      machine_type: [n1-standard-16]
  flags:
    cloud: GCP
    iperf_sending_thread_count: 5
    iperf_runtime_in_seconds: 60
  # vm_groups:
    #   vm_1:
    #     vm_spec: *default_machine
    #     disk_spec: *default_50_gb
    #   vm_2:
    #     vm_spec: *default_machine
    #     disk_spec: *default_50_gb
    