#import anchors.yaml
#benchmark netperf
netperf:
  description: Run TCP_RR
  # https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/wiki/Plotting-Netperf-CDFs
  flag_matrix: fmatrix
  flag_matrix_filters:
      fmatrix: "zones != extra_zones"
  flag_matrix_defs:
      fmatrix:
        zones: *gcp_zones_east1
        extra_zones: *gcp_zones_east1
        machine_type: *gcp_machine_types_small
  flags:
    netperf_histogram_buckets: 1000
    netperf_benchmarks: TCP_RR