#import anchors.yaml
#benchmark ping

ping:
  flag_matrix: fmatrix
  flag_matrix_filters:
      fmatrix: "zones < extra_zones"
  flag_matrix_defs:
      fmatrix:
        zones: *gcp_zones_west1
        extra_zones: *gcp_zones_west1
        machine_type: [n1-standard-16]
        
  flags:
    cloud: GCP
    