---
- hosts: all
  become: no
  #strategy: debug
  #gather_facts: False
  gather_facts: True

  vars_files:
    - vars/main.yml

      #roles:
      #- role: ansible-role-mysql
      #become: True

      #- role: ansible_role_mulval
      #become: False

  tasks:
    # experiment stuff
    - include_tasks: setup.yml
      tags: [setup]
      #- include_tasks: run.yml 
      #tags: run   
