---
- hosts: 127.0.0.1
  connection: local
  #- hosts: all
  become: no
  #strategy: debug
  #gather_facts: False
  gather_facts: True

  vars_files:
    - vars/main.yml

      #roles:
    #    - role: ansible-role-core
    #  become: False


      #  tasks:
    # experiment stuff
  - include_tasks: setup-cac.yml
      tags: 
      - setup
      - work
      - cac

    #- include_tasks: run.yml 
    #  tags: run   
