# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "mulval" do |config|
  
  config.vm.box = "generic/ubuntu1804"
  config.vm.synced_folder '.', '/vagrant', disabled: true
  config.ssh.insert_key = false
  
  config.vm.hostname = "mulval" 
  config.vm.network :private_network, ip: "192.168.42.42" 
  
  # Run Ansible from the Vagrant Host
  config.vm.provision "ansible" do |ansible|
    ansible.compatibility_mode = "2.0"
    ansible.playbook = "playbooks/provision.yml"
    ansible.inventory_path = "inventory"
    ansible.limit = "all"
    ansible.verbose = false 
  end

end

end
