# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.network :private_network, ip: "192.168.0.115"
  BOX_COUNT = 1
#  (1..BOX_COUNT).each do |machine_id|
    config.vm.define "influx1" do |machine|
      machine.vm.hostname = "influx1"

      machine.vm.provider "virtualbox" do |v|
        v.memory = 512
        v.cpus = 1
#      end

      #if machine_id == BOX_COUNT
        machine.vm.provision "ansible" do |ansible|
          ansible.playbook = "playbooks/provision.yml"
          ansible.sudo = true
 #       end
      end

    end
  end
end
